namespace QLKH
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtGiaThanh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSoLuong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenHang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaHang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnBoQua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLuu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXuatPDF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXuatExcel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgvHangHoa = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHangHoa)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.txtGiaThanh);
            this.bunifuPanel1.Controls.Add(this.txtSoLuong);
            this.bunifuPanel1.Controls.Add(this.txtTenHang);
            this.bunifuPanel1.Controls.Add(this.txtMaHang);
            this.bunifuPanel1.Controls.Add(this.label4);
            this.bunifuPanel1.Controls.Add(this.label3);
            this.bunifuPanel1.Controls.Add(this.label2);
            this.bunifuPanel1.Controls.Add(this.label1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(800, 181);
            this.bunifuPanel1.TabIndex = 0;
            this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
            // 
            // txtGiaThanh
            // 
            this.txtGiaThanh.AcceptsReturn = false;
            this.txtGiaThanh.AcceptsTab = false;
            this.txtGiaThanh.AnimationSpeed = 200;
            this.txtGiaThanh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGiaThanh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGiaThanh.BackColor = System.Drawing.Color.Transparent;
            this.txtGiaThanh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGiaThanh.BackgroundImage")));
            this.txtGiaThanh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGiaThanh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGiaThanh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGiaThanh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtGiaThanh.BorderRadius = 1;
            this.txtGiaThanh.BorderThickness = 1;
            this.txtGiaThanh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGiaThanh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaThanh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGiaThanh.DefaultText = "";
            this.txtGiaThanh.FillColor = System.Drawing.Color.White;
            this.txtGiaThanh.HideSelection = true;
            this.txtGiaThanh.IconLeft = null;
            this.txtGiaThanh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaThanh.IconPadding = 10;
            this.txtGiaThanh.IconRight = null;
            this.txtGiaThanh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaThanh.Lines = new string[0];
            this.txtGiaThanh.Location = new System.Drawing.Point(528, 124);
            this.txtGiaThanh.MaxLength = 32767;
            this.txtGiaThanh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGiaThanh.Modified = false;
            this.txtGiaThanh.Multiline = false;
            this.txtGiaThanh.Name = "txtGiaThanh";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaThanh.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGiaThanh.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaThanh.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGiaThanh.OnIdleState = stateProperties4;
            this.txtGiaThanh.Padding = new System.Windows.Forms.Padding(3);
            this.txtGiaThanh.PasswordChar = '\0';
            this.txtGiaThanh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGiaThanh.PlaceholderText = "";
            this.txtGiaThanh.ReadOnly = false;
            this.txtGiaThanh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGiaThanh.SelectedText = "";
            this.txtGiaThanh.SelectionLength = 0;
            this.txtGiaThanh.SelectionStart = 0;
            this.txtGiaThanh.ShortcutsEnabled = true;
            this.txtGiaThanh.Size = new System.Drawing.Size(260, 26);
            this.txtGiaThanh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGiaThanh.TabIndex = 2;
            this.txtGiaThanh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGiaThanh.TextMarginBottom = 0;
            this.txtGiaThanh.TextMarginLeft = 3;
            this.txtGiaThanh.TextMarginTop = 0;
            this.txtGiaThanh.TextPlaceholder = "";
            this.txtGiaThanh.UseSystemPasswordChar = false;
            this.txtGiaThanh.WordWrap = true;
            this.txtGiaThanh.TextChanged += new System.EventHandler(this.txtGiaThanh_TextChanged);
            // 
            // txtSoLuong
            // 
            this.txtSoLuong.AcceptsReturn = false;
            this.txtSoLuong.AcceptsTab = false;
            this.txtSoLuong.AnimationSpeed = 200;
            this.txtSoLuong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoLuong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoLuong.BackColor = System.Drawing.Color.Transparent;
            this.txtSoLuong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoLuong.BackgroundImage")));
            this.txtSoLuong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSoLuong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSoLuong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoLuong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSoLuong.BorderRadius = 1;
            this.txtSoLuong.BorderThickness = 1;
            this.txtSoLuong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoLuong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSoLuong.DefaultText = "";
            this.txtSoLuong.FillColor = System.Drawing.Color.White;
            this.txtSoLuong.HideSelection = true;
            this.txtSoLuong.IconLeft = null;
            this.txtSoLuong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.IconPadding = 10;
            this.txtSoLuong.IconRight = null;
            this.txtSoLuong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.Lines = new string[0];
            this.txtSoLuong.Location = new System.Drawing.Point(528, 89);
            this.txtSoLuong.MaxLength = 32767;
            this.txtSoLuong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoLuong.Modified = false;
            this.txtSoLuong.Multiline = false;
            this.txtSoLuong.Name = "txtSoLuong";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoLuong.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnIdleState = stateProperties8;
            this.txtSoLuong.Padding = new System.Windows.Forms.Padding(3);
            this.txtSoLuong.PasswordChar = '\0';
            this.txtSoLuong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoLuong.PlaceholderText = "";
            this.txtSoLuong.ReadOnly = false;
            this.txtSoLuong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoLuong.SelectedText = "";
            this.txtSoLuong.SelectionLength = 0;
            this.txtSoLuong.SelectionStart = 0;
            this.txtSoLuong.ShortcutsEnabled = true;
            this.txtSoLuong.Size = new System.Drawing.Size(260, 26);
            this.txtSoLuong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoLuong.TabIndex = 2;
            this.txtSoLuong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoLuong.TextMarginBottom = 0;
            this.txtSoLuong.TextMarginLeft = 3;
            this.txtSoLuong.TextMarginTop = 0;
            this.txtSoLuong.TextPlaceholder = "";
            this.txtSoLuong.UseSystemPasswordChar = false;
            this.txtSoLuong.WordWrap = true;
            // 
            // txtTenHang
            // 
            this.txtTenHang.AcceptsReturn = false;
            this.txtTenHang.AcceptsTab = false;
            this.txtTenHang.AnimationSpeed = 200;
            this.txtTenHang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenHang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenHang.BackColor = System.Drawing.Color.Transparent;
            this.txtTenHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenHang.BackgroundImage")));
            this.txtTenHang.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenHang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenHang.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenHang.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenHang.BorderRadius = 1;
            this.txtTenHang.BorderThickness = 1;
            this.txtTenHang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenHang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenHang.DefaultText = "";
            this.txtTenHang.FillColor = System.Drawing.Color.White;
            this.txtTenHang.HideSelection = true;
            this.txtTenHang.IconLeft = null;
            this.txtTenHang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.IconPadding = 10;
            this.txtTenHang.IconRight = null;
            this.txtTenHang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.Lines = new string[0];
            this.txtTenHang.Location = new System.Drawing.Point(528, 18);
            this.txtTenHang.MaxLength = 32767;
            this.txtTenHang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenHang.Modified = false;
            this.txtTenHang.Multiline = false;
            this.txtTenHang.Name = "txtTenHang";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenHang.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnIdleState = stateProperties12;
            this.txtTenHang.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenHang.PasswordChar = '\0';
            this.txtTenHang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenHang.PlaceholderText = "";
            this.txtTenHang.ReadOnly = false;
            this.txtTenHang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenHang.SelectedText = "";
            this.txtTenHang.SelectionLength = 0;
            this.txtTenHang.SelectionStart = 0;
            this.txtTenHang.ShortcutsEnabled = true;
            this.txtTenHang.Size = new System.Drawing.Size(260, 27);
            this.txtTenHang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenHang.TabIndex = 2;
            this.txtTenHang.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenHang.TextMarginBottom = 0;
            this.txtTenHang.TextMarginLeft = 3;
            this.txtTenHang.TextMarginTop = 0;
            this.txtTenHang.TextPlaceholder = "";
            this.txtTenHang.UseSystemPasswordChar = false;
            this.txtTenHang.WordWrap = true;
            // 
            // txtMaHang
            // 
            this.txtMaHang.AcceptsReturn = false;
            this.txtMaHang.AcceptsTab = false;
            this.txtMaHang.AnimationSpeed = 200;
            this.txtMaHang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaHang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaHang.BackColor = System.Drawing.Color.Transparent;
            this.txtMaHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaHang.BackgroundImage")));
            this.txtMaHang.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaHang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaHang.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaHang.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaHang.BorderRadius = 1;
            this.txtMaHang.BorderThickness = 1;
            this.txtMaHang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaHang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaHang.DefaultText = "";
            this.txtMaHang.FillColor = System.Drawing.Color.White;
            this.txtMaHang.HideSelection = true;
            this.txtMaHang.IconLeft = null;
            this.txtMaHang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.IconPadding = 10;
            this.txtMaHang.IconRight = null;
            this.txtMaHang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.Lines = new string[0];
            this.txtMaHang.Location = new System.Drawing.Point(528, 51);
            this.txtMaHang.MaxLength = 32767;
            this.txtMaHang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaHang.Modified = false;
            this.txtMaHang.Multiline = false;
            this.txtMaHang.Name = "txtMaHang";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaHang.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnIdleState = stateProperties16;
            this.txtMaHang.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaHang.PasswordChar = '\0';
            this.txtMaHang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaHang.PlaceholderText = "";
            this.txtMaHang.ReadOnly = false;
            this.txtMaHang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaHang.SelectedText = "";
            this.txtMaHang.SelectionLength = 0;
            this.txtMaHang.SelectionStart = 0;
            this.txtMaHang.ShortcutsEnabled = true;
            this.txtMaHang.Size = new System.Drawing.Size(260, 27);
            this.txtMaHang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaHang.TabIndex = 2;
            this.txtMaHang.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaHang.TextMarginBottom = 0;
            this.txtMaHang.TextMarginLeft = 3;
            this.txtMaHang.TextMarginTop = 0;
            this.txtMaHang.TextPlaceholder = "";
            this.txtMaHang.UseSystemPasswordChar = false;
            this.txtMaHang.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label4.Location = new System.Drawing.Point(432, 127);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(83, 20);
            this.label4.TabIndex = 1;
            this.label4.Text = "Gía thành ";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label3.Location = new System.Drawing.Point(434, 93);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(76, 20);
            this.label3.TabIndex = 1;
            this.label3.Text = "Số lượng ";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label2.Location = new System.Drawing.Point(435, 17);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(75, 20);
            this.label2.TabIndex = 1;
            this.label2.Text = "Mã hàng ";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.label1.Location = new System.Drawing.Point(434, 55);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(80, 20);
            this.label1.TabIndex = 1;
            this.label1.Text = "Tên hàng ";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 36F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(67, 13);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(219, 65);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Hàng hóa ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.btnBoQua);
            this.bunifuPanel2.Controls.Add(this.btnLuu);
            this.bunifuPanel2.Controls.Add(this.btnXuatPDF);
            this.bunifuPanel2.Controls.Add(this.btnXuatExcel);
            this.bunifuPanel2.Controls.Add(this.dgvHangHoa);
            this.bunifuPanel2.Controls.Add(this.btnXoa);
            this.bunifuPanel2.Controls.Add(this.btnThem);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 181);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(800, 269);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // btnBoQua
            // 
            this.btnBoQua.AllowAnimations = true;
            this.btnBoQua.AllowMouseEffects = true;
            this.btnBoQua.AllowToggling = false;
            this.btnBoQua.AnimationSpeed = 200;
            this.btnBoQua.AutoGenerateColors = false;
            this.btnBoQua.AutoRoundBorders = false;
            this.btnBoQua.AutoSizeLeftIcon = true;
            this.btnBoQua.AutoSizeRightIcon = true;
            this.btnBoQua.BackColor = System.Drawing.Color.Transparent;
            this.btnBoQua.BackColor1 = System.Drawing.Color.White;
            this.btnBoQua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBoQua.BackgroundImage")));
            this.btnBoQua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoQua.ButtonText = "Bỏ qua ";
            this.btnBoQua.ButtonTextMarginLeft = 0;
            this.btnBoQua.ColorContrastOnClick = 45;
            this.btnBoQua.ColorContrastOnHover = 45;
            this.btnBoQua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBoQua.CustomizableEdges = borderEdges1;
            this.btnBoQua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBoQua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBoQua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBoQua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBoQua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBoQua.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBoQua.ForeColor = System.Drawing.Color.Black;
            this.btnBoQua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBoQua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBoQua.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBoQua.IconMarginLeft = 11;
            this.btnBoQua.IconPadding = 10;
            this.btnBoQua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBoQua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBoQua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBoQua.IconSize = 25;
            this.btnBoQua.IdleBorderColor = System.Drawing.Color.White;
            this.btnBoQua.IdleBorderRadius = 1;
            this.btnBoQua.IdleBorderThickness = 1;
            this.btnBoQua.IdleFillColor = System.Drawing.Color.White;
            this.btnBoQua.IdleIconLeftImage = null;
            this.btnBoQua.IdleIconRightImage = null;
            this.btnBoQua.IndicateFocus = false;
            this.btnBoQua.Location = new System.Drawing.Point(406, 224);
            this.btnBoQua.Name = "btnBoQua";
            this.btnBoQua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBoQua.OnDisabledState.BorderRadius = 1;
            this.btnBoQua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoQua.OnDisabledState.BorderThickness = 1;
            this.btnBoQua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBoQua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBoQua.OnDisabledState.IconLeftImage = null;
            this.btnBoQua.OnDisabledState.IconRightImage = null;
            this.btnBoQua.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBoQua.onHoverState.BorderRadius = 1;
            this.btnBoQua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoQua.onHoverState.BorderThickness = 1;
            this.btnBoQua.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBoQua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBoQua.onHoverState.IconLeftImage = null;
            this.btnBoQua.onHoverState.IconRightImage = null;
            this.btnBoQua.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnBoQua.OnIdleState.BorderRadius = 1;
            this.btnBoQua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoQua.OnIdleState.BorderThickness = 1;
            this.btnBoQua.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnBoQua.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnBoQua.OnIdleState.IconLeftImage = null;
            this.btnBoQua.OnIdleState.IconRightImage = null;
            this.btnBoQua.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBoQua.OnPressedState.BorderRadius = 1;
            this.btnBoQua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoQua.OnPressedState.BorderThickness = 1;
            this.btnBoQua.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBoQua.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBoQua.OnPressedState.IconLeftImage = null;
            this.btnBoQua.OnPressedState.IconRightImage = null;
            this.btnBoQua.Size = new System.Drawing.Size(117, 28);
            this.btnBoQua.TabIndex = 3;
            this.btnBoQua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBoQua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBoQua.TextMarginLeft = 0;
            this.btnBoQua.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBoQua.UseDefaultRadiusAndThickness = true;
            this.btnBoQua.Click += new System.EventHandler(this.btnBoQua_Click);
            // 
            // btnLuu
            // 
            this.btnLuu.AllowAnimations = true;
            this.btnLuu.AllowMouseEffects = true;
            this.btnLuu.AllowToggling = false;
            this.btnLuu.AnimationSpeed = 200;
            this.btnLuu.AutoGenerateColors = false;
            this.btnLuu.AutoRoundBorders = false;
            this.btnLuu.AutoSizeLeftIcon = true;
            this.btnLuu.AutoSizeRightIcon = true;
            this.btnLuu.BackColor = System.Drawing.Color.Transparent;
            this.btnLuu.BackColor1 = System.Drawing.Color.White;
            this.btnLuu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLuu.BackgroundImage")));
            this.btnLuu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.ButtonText = "Lưu ";
            this.btnLuu.ButtonTextMarginLeft = 0;
            this.btnLuu.ColorContrastOnClick = 45;
            this.btnLuu.ColorContrastOnHover = 45;
            this.btnLuu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLuu.CustomizableEdges = borderEdges2;
            this.btnLuu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLuu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLuu.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLuu.ForeColor = System.Drawing.Color.Black;
            this.btnLuu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLuu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLuu.IconMarginLeft = 11;
            this.btnLuu.IconPadding = 10;
            this.btnLuu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLuu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLuu.IconSize = 25;
            this.btnLuu.IdleBorderColor = System.Drawing.Color.White;
            this.btnLuu.IdleBorderRadius = 1;
            this.btnLuu.IdleBorderThickness = 1;
            this.btnLuu.IdleFillColor = System.Drawing.Color.White;
            this.btnLuu.IdleIconLeftImage = null;
            this.btnLuu.IdleIconRightImage = null;
            this.btnLuu.IndicateFocus = false;
            this.btnLuu.Location = new System.Drawing.Point(144, 224);
            this.btnLuu.Name = "btnLuu";
            this.btnLuu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuu.OnDisabledState.BorderRadius = 1;
            this.btnLuu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnDisabledState.BorderThickness = 1;
            this.btnLuu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuu.OnDisabledState.IconLeftImage = null;
            this.btnLuu.OnDisabledState.IconRightImage = null;
            this.btnLuu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLuu.onHoverState.BorderRadius = 1;
            this.btnLuu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.onHoverState.BorderThickness = 1;
            this.btnLuu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLuu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLuu.onHoverState.IconLeftImage = null;
            this.btnLuu.onHoverState.IconRightImage = null;
            this.btnLuu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnLuu.OnIdleState.BorderRadius = 1;
            this.btnLuu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnIdleState.BorderThickness = 1;
            this.btnLuu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLuu.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnLuu.OnIdleState.IconLeftImage = null;
            this.btnLuu.OnIdleState.IconRightImage = null;
            this.btnLuu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuu.OnPressedState.BorderRadius = 1;
            this.btnLuu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnPressedState.BorderThickness = 1;
            this.btnLuu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLuu.OnPressedState.IconLeftImage = null;
            this.btnLuu.OnPressedState.IconRightImage = null;
            this.btnLuu.Size = new System.Drawing.Size(117, 28);
            this.btnLuu.TabIndex = 2;
            this.btnLuu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLuu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLuu.TextMarginLeft = 0;
            this.btnLuu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLuu.UseDefaultRadiusAndThickness = true;
            this.btnLuu.Click += new System.EventHandler(this.btnLuu_Click);
            // 
            // btnXuatPDF
            // 
            this.btnXuatPDF.AllowAnimations = true;
            this.btnXuatPDF.AllowMouseEffects = true;
            this.btnXuatPDF.AllowToggling = false;
            this.btnXuatPDF.AnimationSpeed = 200;
            this.btnXuatPDF.AutoGenerateColors = false;
            this.btnXuatPDF.AutoRoundBorders = false;
            this.btnXuatPDF.AutoSizeLeftIcon = true;
            this.btnXuatPDF.AutoSizeRightIcon = true;
            this.btnXuatPDF.BackColor = System.Drawing.Color.Transparent;
            this.btnXuatPDF.BackColor1 = System.Drawing.Color.White;
            this.btnXuatPDF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXuatPDF.BackgroundImage")));
            this.btnXuatPDF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatPDF.ButtonText = "Xuất PDF";
            this.btnXuatPDF.ButtonTextMarginLeft = 0;
            this.btnXuatPDF.ColorContrastOnClick = 45;
            this.btnXuatPDF.ColorContrastOnHover = 45;
            this.btnXuatPDF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnXuatPDF.CustomizableEdges = borderEdges3;
            this.btnXuatPDF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXuatPDF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatPDF.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatPDF.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatPDF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXuatPDF.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXuatPDF.ForeColor = System.Drawing.Color.Black;
            this.btnXuatPDF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXuatPDF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatPDF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXuatPDF.IconMarginLeft = 11;
            this.btnXuatPDF.IconPadding = 10;
            this.btnXuatPDF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXuatPDF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatPDF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXuatPDF.IconSize = 25;
            this.btnXuatPDF.IdleBorderColor = System.Drawing.Color.White;
            this.btnXuatPDF.IdleBorderRadius = 1;
            this.btnXuatPDF.IdleBorderThickness = 1;
            this.btnXuatPDF.IdleFillColor = System.Drawing.Color.White;
            this.btnXuatPDF.IdleIconLeftImage = null;
            this.btnXuatPDF.IdleIconRightImage = null;
            this.btnXuatPDF.IndicateFocus = false;
            this.btnXuatPDF.Location = new System.Drawing.Point(537, 224);
            this.btnXuatPDF.Name = "btnXuatPDF";
            this.btnXuatPDF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatPDF.OnDisabledState.BorderRadius = 1;
            this.btnXuatPDF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatPDF.OnDisabledState.BorderThickness = 1;
            this.btnXuatPDF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatPDF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatPDF.OnDisabledState.IconLeftImage = null;
            this.btnXuatPDF.OnDisabledState.IconRightImage = null;
            this.btnXuatPDF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXuatPDF.onHoverState.BorderRadius = 1;
            this.btnXuatPDF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatPDF.onHoverState.BorderThickness = 1;
            this.btnXuatPDF.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXuatPDF.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXuatPDF.onHoverState.IconLeftImage = null;
            this.btnXuatPDF.onHoverState.IconRightImage = null;
            this.btnXuatPDF.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnXuatPDF.OnIdleState.BorderRadius = 1;
            this.btnXuatPDF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatPDF.OnIdleState.BorderThickness = 1;
            this.btnXuatPDF.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnXuatPDF.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnXuatPDF.OnIdleState.IconLeftImage = null;
            this.btnXuatPDF.OnIdleState.IconRightImage = null;
            this.btnXuatPDF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXuatPDF.OnPressedState.BorderRadius = 1;
            this.btnXuatPDF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatPDF.OnPressedState.BorderThickness = 1;
            this.btnXuatPDF.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXuatPDF.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXuatPDF.OnPressedState.IconLeftImage = null;
            this.btnXuatPDF.OnPressedState.IconRightImage = null;
            this.btnXuatPDF.Size = new System.Drawing.Size(117, 28);
            this.btnXuatPDF.TabIndex = 1;
            this.btnXuatPDF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXuatPDF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXuatPDF.TextMarginLeft = 0;
            this.btnXuatPDF.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXuatPDF.UseDefaultRadiusAndThickness = true;
            // 
            // btnXuatExcel
            // 
            this.btnXuatExcel.AllowAnimations = true;
            this.btnXuatExcel.AllowMouseEffects = true;
            this.btnXuatExcel.AllowToggling = false;
            this.btnXuatExcel.AnimationSpeed = 200;
            this.btnXuatExcel.AutoGenerateColors = false;
            this.btnXuatExcel.AutoRoundBorders = false;
            this.btnXuatExcel.AutoSizeLeftIcon = true;
            this.btnXuatExcel.AutoSizeRightIcon = true;
            this.btnXuatExcel.BackColor = System.Drawing.Color.Transparent;
            this.btnXuatExcel.BackColor1 = System.Drawing.Color.White;
            this.btnXuatExcel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXuatExcel.BackgroundImage")));
            this.btnXuatExcel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatExcel.ButtonText = "Xuất Excel";
            this.btnXuatExcel.ButtonTextMarginLeft = 0;
            this.btnXuatExcel.ColorContrastOnClick = 45;
            this.btnXuatExcel.ColorContrastOnHover = 45;
            this.btnXuatExcel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnXuatExcel.CustomizableEdges = borderEdges4;
            this.btnXuatExcel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXuatExcel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatExcel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatExcel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatExcel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXuatExcel.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXuatExcel.ForeColor = System.Drawing.Color.Black;
            this.btnXuatExcel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXuatExcel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatExcel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXuatExcel.IconMarginLeft = 11;
            this.btnXuatExcel.IconPadding = 10;
            this.btnXuatExcel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXuatExcel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXuatExcel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXuatExcel.IconSize = 25;
            this.btnXuatExcel.IdleBorderColor = System.Drawing.Color.White;
            this.btnXuatExcel.IdleBorderRadius = 1;
            this.btnXuatExcel.IdleBorderThickness = 1;
            this.btnXuatExcel.IdleFillColor = System.Drawing.Color.White;
            this.btnXuatExcel.IdleIconLeftImage = null;
            this.btnXuatExcel.IdleIconRightImage = null;
            this.btnXuatExcel.IndicateFocus = false;
            this.btnXuatExcel.Location = new System.Drawing.Point(670, 224);
            this.btnXuatExcel.Name = "btnXuatExcel";
            this.btnXuatExcel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXuatExcel.OnDisabledState.BorderRadius = 1;
            this.btnXuatExcel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatExcel.OnDisabledState.BorderThickness = 1;
            this.btnXuatExcel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXuatExcel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXuatExcel.OnDisabledState.IconLeftImage = null;
            this.btnXuatExcel.OnDisabledState.IconRightImage = null;
            this.btnXuatExcel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXuatExcel.onHoverState.BorderRadius = 1;
            this.btnXuatExcel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatExcel.onHoverState.BorderThickness = 1;
            this.btnXuatExcel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXuatExcel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXuatExcel.onHoverState.IconLeftImage = null;
            this.btnXuatExcel.onHoverState.IconRightImage = null;
            this.btnXuatExcel.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnXuatExcel.OnIdleState.BorderRadius = 1;
            this.btnXuatExcel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatExcel.OnIdleState.BorderThickness = 1;
            this.btnXuatExcel.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnXuatExcel.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnXuatExcel.OnIdleState.IconLeftImage = null;
            this.btnXuatExcel.OnIdleState.IconRightImage = null;
            this.btnXuatExcel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXuatExcel.OnPressedState.BorderRadius = 1;
            this.btnXuatExcel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXuatExcel.OnPressedState.BorderThickness = 1;
            this.btnXuatExcel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXuatExcel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXuatExcel.OnPressedState.IconLeftImage = null;
            this.btnXuatExcel.OnPressedState.IconRightImage = null;
            this.btnXuatExcel.Size = new System.Drawing.Size(118, 28);
            this.btnXuatExcel.TabIndex = 1;
            this.btnXuatExcel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXuatExcel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXuatExcel.TextMarginLeft = 0;
            this.btnXuatExcel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXuatExcel.UseDefaultRadiusAndThickness = true;
            // 
            // dgvHangHoa
            // 
            this.dgvHangHoa.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvHangHoa.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvHangHoa.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHangHoa.BackgroundColor = System.Drawing.Color.White;
            this.dgvHangHoa.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvHangHoa.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvHangHoa.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvHangHoa.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvHangHoa.ColumnHeadersHeight = 40;
            this.dgvHangHoa.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvHangHoa.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvHangHoa.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvHangHoa.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvHangHoa.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvHangHoa.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvHangHoa.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvHangHoa.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvHangHoa.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvHangHoa.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvHangHoa.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvHangHoa.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvHangHoa.CurrentTheme.Name = null;
            this.dgvHangHoa.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvHangHoa.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvHangHoa.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvHangHoa.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvHangHoa.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvHangHoa.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvHangHoa.EnableHeadersVisualStyles = false;
            this.dgvHangHoa.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvHangHoa.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvHangHoa.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvHangHoa.HeaderForeColor = System.Drawing.Color.White;
            this.dgvHangHoa.Location = new System.Drawing.Point(3, 6);
            this.dgvHangHoa.Name = "dgvHangHoa";
            this.dgvHangHoa.RowHeadersVisible = false;
            this.dgvHangHoa.RowTemplate.Height = 40;
            this.dgvHangHoa.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvHangHoa.Size = new System.Drawing.Size(794, 198);
            this.dgvHangHoa.TabIndex = 0;
            this.dgvHangHoa.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvHangHoa.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvHangHoa_CellContentClick);
            // 
            // btnXoa
            // 
            this.btnXoa.AllowAnimations = true;
            this.btnXoa.AllowMouseEffects = true;
            this.btnXoa.AllowToggling = false;
            this.btnXoa.AnimationSpeed = 200;
            this.btnXoa.AutoGenerateColors = false;
            this.btnXoa.AutoRoundBorders = false;
            this.btnXoa.AutoSizeLeftIcon = true;
            this.btnXoa.AutoSizeRightIcon = true;
            this.btnXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnXoa.BackColor1 = System.Drawing.Color.White;
            this.btnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.BackgroundImage")));
            this.btnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.ButtonText = "Xóa ";
            this.btnXoa.ButtonTextMarginLeft = 0;
            this.btnXoa.ColorContrastOnClick = 45;
            this.btnXoa.ColorContrastOnHover = 45;
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnXoa.CustomizableEdges = borderEdges5;
            this.btnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXoa.ForeColor = System.Drawing.Color.Black;
            this.btnXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoa.IconMarginLeft = 11;
            this.btnXoa.IconPadding = 10;
            this.btnXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoa.IconSize = 25;
            this.btnXoa.IdleBorderColor = System.Drawing.Color.White;
            this.btnXoa.IdleBorderRadius = 1;
            this.btnXoa.IdleBorderThickness = 1;
            this.btnXoa.IdleFillColor = System.Drawing.Color.White;
            this.btnXoa.IdleIconLeftImage = null;
            this.btnXoa.IdleIconRightImage = null;
            this.btnXoa.IndicateFocus = false;
            this.btnXoa.Location = new System.Drawing.Point(276, 224);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.OnDisabledState.BorderRadius = 1;
            this.btnXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnDisabledState.BorderThickness = 1;
            this.btnXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.OnDisabledState.IconLeftImage = null;
            this.btnXoa.OnDisabledState.IconRightImage = null;
            this.btnXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.BorderRadius = 1;
            this.btnXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.onHoverState.BorderThickness = 1;
            this.btnXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.onHoverState.IconLeftImage = null;
            this.btnXoa.onHoverState.IconRightImage = null;
            this.btnXoa.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnXoa.OnIdleState.BorderRadius = 1;
            this.btnXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnIdleState.BorderThickness = 1;
            this.btnXoa.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnXoa.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnXoa.OnIdleState.IconLeftImage = null;
            this.btnXoa.OnIdleState.IconRightImage = null;
            this.btnXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.BorderRadius = 1;
            this.btnXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnPressedState.BorderThickness = 1;
            this.btnXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnPressedState.IconLeftImage = null;
            this.btnXoa.OnPressedState.IconRightImage = null;
            this.btnXoa.Size = new System.Drawing.Size(117, 28);
            this.btnXoa.TabIndex = 1;
            this.btnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoa.TextMarginLeft = 0;
            this.btnXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoa.UseDefaultRadiusAndThickness = true;
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);
            // 
            // btnThem
            // 
            this.btnThem.AllowAnimations = true;
            this.btnThem.AllowMouseEffects = true;
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = false;
            this.btnThem.AutoRoundBorders = false;
            this.btnThem.AutoSizeLeftIcon = true;
            this.btnThem.AutoSizeRightIcon = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.White;
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm ";
            this.btnThem.ButtonTextMarginLeft = 0;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges6;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThem.ForeColor = System.Drawing.Color.Black;
            this.btnThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 5;
            this.btnThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThem.IconSize = 25;
            this.btnThem.IdleBorderColor = System.Drawing.Color.White;
            this.btnThem.IdleBorderRadius = 1;
            this.btnThem.IdleBorderThickness = 1;
            this.btnThem.IdleFillColor = System.Drawing.Color.White;
            this.btnThem.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThem.IdleIconLeftImage")));
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(12, 224);
            this.btnThem.Name = "btnThem";
            this.btnThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.OnDisabledState.BorderRadius = 1;
            this.btnThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnDisabledState.BorderThickness = 1;
            this.btnThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.OnDisabledState.IconLeftImage = null;
            this.btnThem.OnDisabledState.IconRightImage = null;
            this.btnThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.BorderRadius = 1;
            this.btnThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.onHoverState.BorderThickness = 1;
            this.btnThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThem.onHoverState.IconLeftImage = null;
            this.btnThem.onHoverState.IconRightImage = null;
            this.btnThem.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.BorderRadius = 1;
            this.btnThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnIdleState.BorderThickness = 1;
            this.btnThem.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnThem.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThem.OnIdleState.IconLeftImage")));
            this.btnThem.OnIdleState.IconRightImage = null;
            this.btnThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.BorderRadius = 1;
            this.btnThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnPressedState.BorderThickness = 1;
            this.btnThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnPressedState.IconLeftImage = null;
            this.btnThem.OnPressedState.IconRightImage = null;
            this.btnThem.Size = new System.Drawing.Size(117, 28);
            this.btnThem.TabIndex = 1;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThem.TextMarginLeft = 0;
            this.btnThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThem.UseDefaultRadiusAndThickness = true;
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "Form1";
            this.Text = "Hàng hóa   ";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvHangHoa)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXuatExcel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXuatPDF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvHangHoa;
        private Bunifu.UI.WinForms.BunifuTextBox txtGiaThanh;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoLuong;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenHang;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaHang;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLuu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBoQua;
    }
}

